name: apply terraform resources

on:
  push:
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: login to azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Plan Terraform deployment
      run: terraform plan

    - name: apply Terraform resources
      run: terraform apply -auto-approve